### ISSUE TITLE
Missing space after // in commend (maybe easter eggs?)

### ISSUE THREAD

**Issue by suraneti** [react-native-community/upgrade-support#53]
## Upgrading version

0.62.2

## Description

I've found a missing space after // haha.
 
`Line 192:  //noinspection GradleDynamicVersion` in android/app/build.gradle file.

**Comment by matt-oakes** [comment]
👋 This line is there to surpress warnings from the InteliJ (Android Studio) lint tool.

It is usually frowned upon to use "dynamic" version specifiers (the `+` sign at the end of the `implementation` line). This is because Gradle does not have the concept of lockfiles and using dynamic version specifiers leads to non-deterministic builds.

This comment is to suppress the warning for the React Native dependency specification. Because this dependency is pull directly from the `node_modules` folder, the version doesn't need to be specified.

The reason there is no space, is because that is the [format required by the lint tool to suppress  the warnings](https://stackoverflow.com/questions/24572937/how-to-suppress-android-lint-warning-in-gradle-script/24590607). This is just the same as needing to use three forward slashes to suppress a TypeScript error (`/// @ts-ignore`).

**Comment by suraneti** [comment]
@matt-oakes thank you for your explanation.
